version: '3.7'

services:

  test:
    container_name: "test"
    build:
      context: ./web
      dockerfile: Dockerfile.test
    env_file:
      - .env
    networks:
      - custom
    depends_on:
      db_test:
        condition: service_started
      redis:
        condition: service_started


  db_test:
    container_name: "db_test"
    image: postgres:15.1-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}
    networks:
      - custom
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 70s

  redis:
    container_name: "redis"
    image: redis:7-alpine
    env_file:
      - .env
    command: --port ${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    networks:
      - custom

networks:
  custom:
    driver: bridge
