version: '3.5'

services:

  web:
    container_name: "web"
    build: ./web
    env_file:
      - .env
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 8000:1111
    networks:
      - custom
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: "db"
    image: postgres:13-alpine
    volumes:
      - ./db_dev/:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - custom
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 70s

volumes:
  db_dev:
    name: db_dev

networks:
  custom:
    driver: bridge