FROM python:3.10-slim

WORKDIR /usr/src/app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN apt-get update

RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
    RUN pip install -r requirements.txt

COPY . /usr/src/app/

COPY ./tests_entrypoint.sh /usr/src/app/tests_entrypoint.sh
RUN chmod a+x ./tests_entrypoint.sh


ENTRYPOINT ["/usr/src/app/tests_entrypoint.sh"]
